apiVersion: v1
kind: Pod
metadata: 
        name: myapp-redis-pod
        labels:
                app: myapp
                type: front-end
spec:
        containers:
                - name: redis-container
                  image: redis
