apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
